# Generated by Django 2.1.4 on 2018-12-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField(max_length=11, verbose_name='手机号')),
                ('real_name', models.CharField(max_length=12, verbose_name='真实姓名')),
            ],
            options={
                'verbose_name': '审核通过用户',
                'db_table': 'audit_table',
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField(max_length=11, verbose_name='手机号')),
                ('real_name', models.CharField(max_length=12, verbose_name='真实姓名')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号码')),
                ('id_card_posi', models.CharField(max_length=16, verbose_name='身份证正面云链接')),
                ('id_card_nega', models.CharField(max_length=16, verbose_name='身份证反面云链接')),
                ('hand_card_posi', models.CharField(max_length=16, verbose_name='手持身份证云链接')),
            ],
            options={
                'verbose_name': '未审核用户',
                'db_table': 'unaudit_table',
            },
        ),
        migrations.CreateModel(
            name='Unaudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField(max_length=11, verbose_name='手机号')),
                ('real_name', models.CharField(max_length=12, verbose_name='真实姓名')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号码')),
                ('id_card_posi', models.CharField(max_length=16, verbose_name='身份证正面云链接')),
                ('id_card_nega', models.CharField(max_length=16, verbose_name='身份证反面云链接')),
                ('hand_card_posi', models.CharField(max_length=16, verbose_name='手持身份证云链接')),
            ],
            options={
                'verbose_name': '未审核用户',
                'db_table': 'unaudit_table',
            },
        ),
    ]
