# Generated by Django 2.1.4 on 2018-12-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='privacy',
            table='privacy_table',
        ),
    ]
